### ISSUE TITLE
What is chihiro-api

### ISSUE THREAD

**Issue by wuzzapcom** [snipem/psnprices#10]
Hello. Looked at your code and found, that you have variable 
`apiRoot = "https://store.playstation.com/chihiro-api"`. 
Is `chihiro-api` some account identifier which allowed by Sony returning of JSON answers? If it is so, how can I get my own identifier?

**Comment by snipem** [comment]
chihiro-api is the path for the API. There is no authentication in place on PSNs side. You should be able to use the API as well.
